import os
import subprocess
import json
import boto3
from datetime import datetime

# ----------------------------
# ENV VARS FROM ECS
# ----------------------------
SESSION_ID = os.environ["SESSION_ID"]
REPO = os.environ["REPO"]
PROMPT = os.environ["PROMPT"]
S3_BUCKET = os.environ["S3_BUCKET"]

# ----------------------------
# AWS CLIENTS
# ----------------------------
s3 = boto3.client("s3")


# ----------------------------
# STEP 1: CLONE REPO
# ----------------------------
def clone_repo():
    repo_url = f"https://github.com/{REPO}.git"
    path = "/tmp/repo"

    subprocess.run(["git", "clone", repo_url, path], check=True)

    return path


# ----------------------------
# STEP 2: RUN "CODEX" (SIMULATED FOR POC)
# Replace this with OpenAI API call later
# ----------------------------
def run_codex(prompt, repo_path):

    file_path = f"{repo_path}/generated.py"

    code = f'''"""
Generated by Codex Agent
Prompt: {prompt}
"""

def hello():
    print("Hello from Codex agent!")
'''

    with open(file_path, "w") as f:
        f.write(code)

    return file_path


# ----------------------------
# STEP 3: COMMIT + PUSH
# ----------------------------
def commit_changes(repo_path):

    branch = f"agent/{SESSION_ID}"

    subprocess.run(["git", "checkout", "-b", branch], cwd=repo_path, check=True)

    subprocess.run(["git", "add", "."], cwd=repo_path, check=True)

    subprocess.run(
        ["git", "commit", "-m", f"Codex changes for session {SESSION_ID}"],
        cwd=repo_path,
        check=True
    )

    subprocess.run(["git", "push", "origin", branch], cwd=repo_path, check=True)

    return branch


# ----------------------------
# STEP 4: WRITE RESULT TO S3
# ----------------------------
def write_result(branch):

    result = {
        "sessionId": SESSION_ID,
        "repo": REPO,
        "branch": branch,
        "status": "COMPLETED",
        "timestamp": datetime.utcnow().isoformat()
    }

    s3.put_object(
        Bucket=S3_BUCKET,
        Key=f"{SESSION_ID}/result.json",
        Body=json.dumps(result)
    )


# ----------------------------
# MAIN EXECUTION
# ----------------------------
def main():

    print("Starting agent...")
    print("Session:", SESSION_ID)
    print("Repo:", REPO)
    print("Prompt:", PROMPT)

    repo_path = clone_repo()

    run_codex(PROMPT, repo_path)

    branch = commit_changes(repo_path)

    write_result(branch)

    print("Agent completed successfully.")


if __name__ == "__main__":
    main()